In [1]:
lista = [5,6,9,8,7,4,65,2,2,56,46,54]
print(lista)

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]


In [2]:
2 in lista

True

In [3]:
35 in lista

False

In [4]:
lista[0]

5

In [5]:
lista[-1]

54

In [6]:
lista[2:4]

[9, 8]

In [7]:
lista[:5]

[5, 6, 9, 8, 7]

In [8]:
lista[4:]

[7, 4, 65, 2, 2, 56, 46, 54]

In [9]:
lista[:]

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]

In [10]:
import numpy as np

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [12]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
len(a)

4

In [14]:
min(a)

1

In [15]:
max(a)

4

In [16]:
b = np.array([[1,2,3],[5,6,4],[7,5,2]])
b

array([[1, 2, 3],
       [5, 6, 4],
       [7, 5, 2]])

In [17]:
b[0]

array([1, 2, 3])

In [18]:
b[:,1]

array([2, 6, 5])

In [19]:
b[2,2]

2

# Revisar la indexación de matrices (filas columnas)

In [20]:
b[0:2, 1:3]

array([[2, 3],
       [6, 4]])

In [21]:
a = np.random.rand(5,5)
a

array([[0.02226661, 0.23971379, 0.56209789, 0.3569935 , 0.3243083 ],
       [0.28468744, 0.44605932, 0.90581145, 0.86548222, 0.15974594],
       [0.12466812, 0.41797103, 0.80643509, 0.38666037, 0.02686694],
       [0.73865327, 0.00321154, 0.3375429 , 0.68889932, 0.31741889],
       [0.7320236 , 0.38810283, 0.22330797, 0.15636905, 0.02152751]])

In [22]:
a.shape

(5, 5)

In [23]:
b  = np.random.rand(5,5)
b

array([[0.10386513, 0.35166832, 0.32788565, 0.07587138, 0.70266894],
       [0.63187396, 0.84880251, 0.77464611, 0.15685826, 0.02581687],
       [0.79301534, 0.312659  , 0.72741144, 0.45206623, 0.65771023],
       [0.93210362, 0.59790338, 0.06891883, 0.19376134, 0.38109064],
       [0.95501542, 0.17281456, 0.03951609, 0.11678927, 0.58544413]])

In [24]:
a + b

array([[0.12613174, 0.59138211, 0.88998354, 0.43286488, 1.02697724],
       [0.9165614 , 1.29486183, 1.68045756, 1.02234048, 0.18556281],
       [0.91768346, 0.73063002, 1.53384653, 0.8387266 , 0.68457717],
       [1.67075688, 0.60111492, 0.40646172, 0.88266067, 0.69850953],
       [1.68703902, 0.5609174 , 0.26282407, 0.27315832, 0.60697164]])

In [25]:
a-b

array([[-0.08159852, -0.11195453,  0.23421224,  0.28112211, -0.37836064],
       [-0.34718652, -0.40274319,  0.13116534,  0.70862396,  0.13392908],
       [-0.66834722,  0.10531203,  0.07902365, -0.06540587, -0.6308433 ],
       [-0.19345035, -0.59469184,  0.26862407,  0.49513798, -0.06367175],
       [-0.22299182,  0.21528827,  0.18379188,  0.03957978, -0.56391662]])

In [26]:
a*b

array([[0.00231272, 0.08429975, 0.18430383, 0.02708559, 0.22788137],
       [0.17988658, 0.37861627, 0.70168331, 0.13575804, 0.00412414],
       [0.09886373, 0.1306824 , 0.58661011, 0.17479609, 0.01767066],
       [0.68850138, 0.00192019, 0.02326306, 0.13348206, 0.12096537],
       [0.69909382, 0.06706982, 0.00882426, 0.01826223, 0.01260315]])

In [27]:
a/b

array([[2.14380039e-01, 6.81647395e-01, 1.71431073e+00, 4.70524565e+00,
        4.61537835e-01],
       [4.50544665e-01, 5.25516025e-01, 1.16932292e+00, 5.51760686e+00,
        6.18765804e+00],
       [1.57207697e-01, 1.33682711e+00, 1.10863680e+00, 8.55317958e-01,
        4.08492023e-02],
       [7.92458319e-01, 5.37132952e-03, 4.89768783e+00, 3.55540123e+00,
        8.32922298e-01],
       [7.66504481e-01, 2.24577617e+00, 5.65106402e+00, 1.33889908e+00,
        3.67712467e-02]])

In [28]:
np.transpose(a)

array([[0.02226661, 0.28468744, 0.12466812, 0.73865327, 0.7320236 ],
       [0.23971379, 0.44605932, 0.41797103, 0.00321154, 0.38810283],
       [0.56209789, 0.90581145, 0.80643509, 0.3375429 , 0.22330797],
       [0.3569935 , 0.86548222, 0.38666037, 0.68889932, 0.15636905],
       [0.3243083 , 0.15974594, 0.02686694, 0.31741889, 0.02152751]])

In [29]:
1/a

array([[ 44.91029298,   4.17164145,   1.77904955,   2.80117147,
          3.08348568],
       [  3.51262421,   2.24185428,   1.10398251,   1.15542524,
          6.25993989],
       [  8.02129715,   2.39251033,   1.24002541,   2.58624905,
         37.22046727],
       [  1.35381517, 311.37747715,   2.96258641,   1.45159092,
          3.1504111 ],
       [  1.36607618,   2.5766367 ,   4.47812044,   6.3951274 ,
         46.45218967]])